spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/refrigerator
    username: fridge_user
    password: fridge_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  docker:
    compose:
      enabled: true
  security:
    user:
      name: fridge_user
      password: fridge_pass
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

logging:
  level:
    root: INFO

jwt:
  secret: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZyaWRnZV91c2VyIn0.sMix6FrXvAufGD9rsQyFAkwg30VKTlCh33ALgZ4Znog

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

