spring:
  application:
    name: refrigerator-api
  profiles:
    active: dev
  datasource:
    username: fridge_user
    password: fridge_pass
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  docker:
    compose:
      enabled: true
  security:
    user:
      name: fridge_user
      password: fridge_pass

server:
  port: 8080

logging:
  level:
    root: INFO

jwt:
  secret: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZyaWRnZV91c2VyIn0.sMix6FrXvAufGD9rsQyFAkwg30VKTlCh33ALgZ4Znog

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

