INSERT INTO good (name, icon, category_id) VALUES
('Apple', '🍎', 1),
('Apricot', '🍑', 1),
('Avocado', '🥑', 1),
('Banana', '🍌', 1),
('Blueberry', '🫐', 1),
('Cherry', '🍒', 1),
('Cherry tomato', '🍅', 1),
('Coconut', '🥥', 1),
('Dragon fruit', '🐉', 1),
('Durian', '🌰', 1),
('Fig', '🍈', 1),
('Grapefruit', '🍊', 1),
('Grapes', '🍇', 1),
('Guava', '🥝', 1),
('Kiwi', '🥝', 1),
('Kumquat', '🍊', 1),
('Lemon', '🍋', 1),
('Lime', '🍋', 1),
('Mandarin', '🍊', 1),
('Mango', '🥭', 1),
('Melon', '🍈', 1),
('Olive', '🫒', 1),
('Orange', '🍊', 1),
('Oriental melon', '🍈', 1),
('Papaya', '🥭', 1),
('Peach', '🍑', 1),
('Pear', '🍐', 1),
('Persimmon', '🍊', 1),
('Pineapple', '🍍', 1),
('Plum', '🍑', 1),
('Pomegranate', '🍎', 1),
('Rambutan', '🌰', 1),
('Strawberry', '🍓', 1),
('Tomato', '🍅', 1),
('Watermelon', '🍉', 1),
('Arugula', '🥗', 2),
('Asparagus', '🥦', 2),
('Bamboo', '🎍', 2),
('Bean sprout', '🌱', 2),
('Beet', '🥗', 2),
('Bell pepper', '🥗', 2),
('Black cabbage', '🥗', 2),
('Bok choy', '🥗', 2),
('Broccoli', '🥗', 2),
('Burdock root', '🥗', 2),
('Cabbage', '🥗', 2),
('Cauliflower', '🥗', 2),
('Celery', '🥗', 2),
('Chard', '🥗', 2),
('Chili pepper', '🥗', 2),
('Chives', '🥗', 2),
('Corn', '🥗', 2),
('Cucumber', '🥗', 2),
('Eggplant', '🥗', 2),
('Endive', '🥗', 2),
('Enoki mushroom', '🥗', 2),
('Ginseng', '🥗', 2),
('Green beans', '🥗', 2),
('Green onion', '🥗', 2),
('Kabocha', '🥗', 2),
('Kale', '🥗', 2),
('King trumpet mushroom', '🥗', 2),
('Kohlrabi', '🥗', 2),
('Leaf lettuce', '🥗', 2),
('Leek', '🥗', 2),
('Lettuce', '🥗', 2),
('Lotus root', '🥗', 2),
('Mushroom', '🥗', 2),
('Napa cabbage', '🥗', 2),
('Onion', '🥗', 2),
('Oyster mushroom', '🥗', 2),
('Pepper', '🥗', 2),
('Perilla leaf', '🥗', 2),
('Potato', '🥗', 2),
('Pumpkin', '🥗', 2),
('Shallot', '🥗', 2),
('Shitake mushroom', '🥗', 2),
('Spinach', '🥗', 2),
('Sprouts', '🥗', 2),
('Sweet potato', '🥗', 2),
('Taro', '🥗', 2),
('Turnip', '🥗', 2),
('White radish', '🥗', 2),
('Zucchini', '🥗', 2),
('Bacon', '🥓', 3),
('Beef', '🥩', 3),
('Chicken', '🍗', 3),
('Chicken breast', '🍗', 3),
('Chicken legs', '🍗', 3),
('Chicken wings', '🍗', 3),
('Chorizo', '🥩', 3),
('Duck', '🥩', 3),
('Ham', '🥩', 3),
('Lamb', '🥩', 3),
('Pepperoni', '🥩', 3),
('Pork', '🥩', 3),
('Pork belly', '🥩', 3),
('Pork leg', '🥩', 3),
('Rib', '🥩', 3),
('Rib eye', '🥩', 3),
('Salami', '🥩', 3),
('Sausages', '🥩', 3),
('Sirloin', '🥩', 3),
('Tenderloin', '🥩', 3),
('Tomahawk', '🥩', 3),
('T-bone', '🥩', 3),
('Abalone', '🦐', 4),
('Anchovy', '🦐', 4),
('Anglerfish', '🦐', 4),
('Catfish', '🦐', 4),
('Caviar', '🦐', 4),
('Clam', '🦐', 4),
('Cockles', '🦐', 4),
('Cod', '🦐', 4),
('Crab', '🦐', 4),
('Cutlassfish', '🦐', 4),
('Cuttlefish', '🦐', 4),
('Dried fish', '🦐', 4),
('Eel', '🦐', 4),
('Fish', '🦐', 4),
('Fish eggs', '🦐', 4),
('Jellyfish', '🦐', 4),
('Lobster', '🦐', 4),
('Mackerel', '🦐', 4),
('Manila clam', '🦐', 4),
('Mussel', '🦐', 4),
('Octopus', '🦐', 4),
('Oyster', '🦐', 4),
('Prawn', '🦐', 4),
('Salmon', '🦐', 4),
('Sardine', '🦐', 4),
('Scallop', '🦐', 4),
('Sea cucumber', '🦐', 4),
('Sea urchin', '🦐', 4),
('Seaweed', '🦐', 4),
('Shrimp', '🦐', 4),
('Snow crab', '🦐', 4),
('Squid', '🦐', 4),
('Tuna', '🦐', 4),
('Whelk', '🦐', 4),
('Almond milk', '🧀', 5),
('Brie', '🧀', 5),
('Bubble tea', '🧀', 5),
('Burrata', '🧀', 5),
('Butter', '🧀', 5),
('Buttermilk', '🧀', 5),
('Cheddar', '🧀', 5),
('Cheese', '🧀', 5),
('Coconut milk', '🧀', 5),
('Cottage cheese', '🧀', 5),
('Cream cheese', '🧀', 5),
('Gorgonzola', '🧀', 5),
('Gouda', '🧀', 5),
('Lassi', '🧀', 5),
('Milk', '🧀', 5),
('Mozzarella', '🧀', 5),
('Parmesan', '🧀', 5),
('Ricotta', '🧀', 5),
('Sour cream', '🧀', 5),
('Soy milk', '🧀', 5),
('Whipped cream', '🧀', 5),
('Yogurt', '🧀', 5),
('Broth', '🍲', 6),
('Burger', '🍲', 6),
('Burrito', '🍲', 6),
('Canned food', '🍲', 6),
('Canned tuna', '🍲', 6),
('Cereal', '🍲', 6),
('Cooked rice', '🍲', 6),
('Crab stick', '🍲', 6),
(' Cup noodles', '🍲', 6),
('Curry', '🍲', 6),
('Dumpling', '🍲', 6),
('Egg', '🍲', 6),
('Fish finger', '🍲', 6),
('Fondue', '🍲', 6),
('Fried chicken', '🍲', 6),
('Fried rice', '🍲', 6),
('Fried shrimp', '🍲', 6),
('Frittata', '🍲', 6),
('Frozen goods', '🍲', 6),
('Gnocchi', '🍲', 6),
('Goulash', '🍲', 6),
('Hotdog', '🍲', 6),
('Instant noodles', '🍲', 6),
('Kebab', '🍲', 6),
('Kimchi', '🍲', 6),
('Lasagna', '🍲', 6),
('Laver', '🍲', 6),
('Launch box', '🍲', 6),
('Minestrone', '🍲', 6),
('Noodles', '🍲', 6),
('Oden', '🍲', 6),
('Onigiri', '🍲', 6),
('Paella', '🍲', 6),
('Pasta', '🍲', 6),
('Pho', '🍲', 6),
('Pickle', '🍲', 6),
('Pizza', '🍲', 6),
('Pork cutlet', '🍲', 6),
('Porridge', '🍲', 6),
('Quail egg', '🍲', 6),
('Risotto', '🍲', 6),
('Salad', '🍲', 6),
('Sandwich', '🍲', 6),
('Sashimi', '🍲', 6),
('Soup', '🍲', 6),
('Spaghetti', '🍲', 6),
('Stew', '🍲', 6),
('Stir-fry', '🍲', 6),
('Summer roll', '🍲', 6),
('Sushi', '🍲', 6),
('Taco', '🍲', 6),
('Tempeh', '🍲', 6),
('Tofu', '🍲', 6),
('Coconut water', '🥤', 7),
('Coffee', '🥤', 7),
('Coffee bean', '🥤', 7),
('Coke', '🥤', 7),
('Energy drink', '🥤', 7),
('Hot chocolate', '🥤', 7),
('Juice', '🥤', 7),
('Lemonade', '🥤', 7),
('Packed fruit juice', '🥤', 7),
('Soda can', '🥤', 7),
('Soft drink', '🥤', 7),
('Sparkling water', '🥤', 7),
('Sports drink', '🥤', 7),
('Tea', '🥤', 7),
('Tonic', '🥤', 7),
('Water', '🥤', 7),
('Beer', '🍷', 8),
('Brandy', '🍷', 8),
('Champagne', '🍷', 8),
('Cocktail', '🍷', 8),
('Gin', '🍷', 8),
('Herbal liqueur', '🍷', 8),
('Liqueur coffee', '🍷', 8),
('Punch', '🍷', 8),
('Rum', '🍷', 8),
('Sake', '🍷', 8),
('Sangria', '🍷', 8),
('Soju', '🍷', 8),
('Tequila', '🍷', 8),
('Vodka', '🍷', 8),
('Whiskey', '🍷', 8),
('Wine', '🍷', 8),
('Agave syrup', '🥫', 9),
('Apple cider vinegar', '🥫', 9),
('Balsamic vinegar', '🥫', 9),
('BBQ sauce', '🥫', 9),
('Brewed vinegar', '🥫', 9),
('Chocolate jam', '🥫', 9),
('Corn syrup', '🥫', 9),
('Fish sauce', '🥫', 9),
('Honey', '🥫', 9),
('Hot sauce', '🥫', 9),
('Jam', '🥫', 9),
('Ketchup', '🥫', 9),
('Lemon juice', '🥫', 9),
('Maple syrup', '🥫', 9),
('Mayonnaise', '🥫', 9),
('Mustard', '🥫', 9),
('Oil', '🥫', 9),
('Olive oil', '🥫', 9),
('Oyster sauce', '🥫', 9),
('Peanut butter', '🥫', 9),
('Pesto', '🥫', 9),
('Salad dressing', '🥫', 9),
('Salsa', '🥫', 9),
('Salt', '🥫', 9),
('Sauce packet', '🥫', 9),
('Soy sauce', '🥫', 9),
('Steak sauce', '🥫', 9),
('Sugar', '🥫', 9),
('Syrup', '🥫', 9),
('Tomato sauce', '🥫', 9),
('Wasabi', '🥫', 9),
('Basil', '🌿', 10),
('Bay leaf', '🌿', 10),
('Black pepper', '🌿', 10),
('Caper', '🌿', 10),
('Chili powder', '🌿', 10),
('Cinnamon', '🌿', 10),
('Coriander', '🌿', 10),
('Cumin', '🌿', 10),
('Curry powder', '🌿', 10),
('Dill', '🌿', 10),
('Fennel', '🌿', 10),
('Garlic', '🌿', 10),
('Ginger', '🌿', 10),
('Minced garlic', '🌿', 10),
('Mint', '🌿', 10),
('Oregano', '🌿', 10),
('Parsley', '🌿', 10),
('Rosemary', '🌿', 10),
('Thyme', '🌿', 10),
('Truffle', '🌿', 10),
('Bagel', '🍞', 11),
('Baguette', '🍞', 11),
('Bread rolls', '🍞', 11),
('Brioche', '🍞', 11),
('Bun', '🍞', 11),
('Ciabatta', '🍞', 11),
('Cinnamon roll', '🍞', 11),
('Crepe', '🍞', 11),
('Croissant', '🍞', 11),
('Donut', '🍞', 11),
('Flatbread', '🍞', 11),
('Focaccia', '🍞', 11),
('Madeleine', '🍞', 11),
('Muffin', '🍞', 11),
('Pancake', '🍞', 11),
('Pie', '🍞', 11),
('Pretzel', '🍞', 11),
('Scone', '🍞', 11),
('Sourdough', '🍞', 11),
('Waffle', '🍞', 11),
('White bread', '🍞', 11),
('Baklava', '🍰', 12),
('Biscuits', '🍰', 12),
('Brownies', '🍰', 12),
('Cake', '🍰', 12),
('Candy', '🍰', 12),
('Caramel', '🍰', 12),
('Chewing gum', '🍰', 12),
('Chocolate', '🍰', 12),
('Churros', '🍰', 12),
('Cookie', '🍰', 12),
('Cracker', '🍰', 12),
('Cupcakes', '🍰', 12),
('Egg tart', '🍰', 12),
('Energy bar', '🍰', 12),
('French fries', '🍰', 12),
('Gummy bear', '🍰', 12),
('Honeycomb', '🍰', 12),
('Ice cream', '🍰', 12),
('Jelly beans', '🍰', 12),
('Lollipop', '🍰', 12),
('Macaron', '🍰', 12),
('Marshmallow', '🍰', 12),
('Nachos', '🍰', 12),
('Popcorn', '🍰', 12),
('Potato chips', '🍰', 12),
('Pudding', '🍰', 12),
('Roll cake', '🍰', 12),
('Shaved ice', '🍰', 12),
('Snacks', '🍰', 12),
('Tiramisu', '🍰', 12),
('Acorn', '🥜', 13),
('Almond', '🥜', 13),
('Brazil nut', '🥜', 13),
('Cacao', '🥜', 13),
('Cashew nut', '🥜', 13),
('Chestnut', '🥜', 13),
('Hazelnut', '🥜', 13),
('Macadamia nut', '🥜', 13),
('Peanut', '🥜', 13),
('Pecan', '🥜', 13),
('Pine nut', '🥜', 13),
('Pistachio', '🥜', 13),
('Pumpkin seed', '🥜', 13),
('Sesame', '🥜', 13),
('Sunflower seed', '🥜', 13),
('Walnut', '🥜', 13),
('Barley', '🌾', 14),
('Black bean', '🌾', 14),
('Buckwheat', '🌾', 14),
('Chia seed', '🌾', 14),
('Chickpea', '🌾', 14),
('Corn starch', '🌾', 14),
('Edamame', '🌾', 14),
('Flour', '🌾', 14),
('Green gram', '🌾', 14),
('Green pea', '🌾', 14),
('Kidney bean', '🌾', 14),
('Lentil', '🌾', 14),
('Oatmeal', '🌾', 14),
('Quinoa', '🌾', 14),
('Red bean', '🌾', 14),
('Rice', '🌾', 14),
('Rye', '🌾', 14),
('Soybean', '🌾', 14),
('Yeast', '🌾', 14),
('Baby food', '📦', 15),
('Baby formula', '📦', 15),
('Baking soda', '📦', 15),
('Cosmetics', '📦', 15),
('Fish oil', '📦', 15),
('Pet food', '📦', 15),
('Pills', '📦', 15),
('Probiotic', '📦', 15),
('Protein', '📦', 15),
('Sheet mask', '📦', 15),
('Vitamins', '📦', 15);